### ISSUE TITLE
enums GLFW_*

### ISSUE THREAD

**Issue by anton-dutov** [DerelictOrg/DerelictGLFW3#10]
Enums not predefined?
How to impl that:

    glfwWindowHint(GLFW_OPENGL_VERSION_MAJOR, 3); 
    glfwWindowHint(GLFW_OPENGL_VERSION_MINOR, 3);

**Comment by mdparker** [comment]
They [are defined](https://github.com/DerelictOrg/DerelictGLFW3/blob/master/source/derelict/glfw3/types.d#L261) and I use them regularly. What sort of problem are you having?

**Comment by anton-dutov** [comment]
By myself i found guide from previous versions where defines are old.  No troubles, just my fault ,sorry =)

    //glfwWindowHint(GLFW_OPENGL_VERSION_MAJOR, 3);
    //glfwWindowHint(GLFW_OPENGL_VERSION_MINOR, 3);
    //glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

**Comment by mdparker** [comment]
Ah, right. I completely overlooked the _OPENGL_ vs _CONTEXT_ bit. Glad you worked it out.
