### ISSUE TITLE
Missing the error enum GLFW_NO_WINDOW_CONTEXT (0x0001000A)

### ISSUE THREAD

**Issue by storm20200** [DerelictOrg/DerelictGLFW3#11]
Hi there, I noticed a missing error code enum GLFW_NO_WINDOW_CONTEXT with the value 0x0001000A. It can be found [here in the documentation](http://www.glfw.org/docs/latest/group__errors.html#gacff24d2757da752ae4c80bf452356487).

**Comment by storm20200** [comment]
I added it to my forked repo [here](https://github.com/storm20200/DerelictGLFW3/commit/b7316363fc4c959412238a44dc21b676dbecf35d), feel free to merge the change :)

**Comment by mdparker** [comment]
Thanks. It's fixed in versions 3.1.2 and 4.0.0-alpha.4.
