### ISSUE TITLE
Missing Field GLFW_CONTEXT_CREATION_API

### ISSUE THREAD

**Issue by Xinmudotmoe** [DerelictOrg/DerelictGLFW3#14]
Use this code to switch to EGL.
```d
glfwWindowHint(GLFW_CONTEXT_CREATION_API, GLFW_EGL_CONTEXT_API);
```
But it will go wrong.
```shell
Error: undefined identifier GLFW_CONTEXT_CREATION_API
```
Defined in [GLFW: Window guide](https://www.glfw.org/docs/latest/window_guide.html#GLFW_CONTEXT_CREATION_API_hint).

**Comment by mdparker** [comment]
I'm no longer maintaining the Derelict packages. The replacement for DerelictGLFW3 is binbc-glfw. I've checked and it isn't missing that constant. You'll also want to use bindbc-opengl. Please read the project README files to see how the set up differs from Derelict:

https://github.com/BindBC/bindbc-glfw
https://code.dlang.org/packages/bindbc-glfw

https://github.com/BindBC/bindbc-opengl
https://code.dlang.org/packages/bindbc-opengl

There are also BindBC packages for FreeType and FreeImage if you need those.
