### ISSUE TITLE
Push new version to the dub registry

### ISSUE THREAD

**Issue by ddude** [DerelictOrg/DerelictGLFW3#6]
Hello! I'm using new features (```glfwGetWin32Window``` and the likes) and they're not yet available when using the version from the dub registry.

**Comment by aldacron** [comment]
Ah, I forgot to merge that functionality into the 3.1 branch as well. Or maybe I had a reason... I don't recall. Anyway, I'm on vacation atm. I'm actually flying back home tomorrow, so I'll see what's going on this weekend when I can get back to my dev box. Maybe I've got some commits there that haven't yet been pushed.

**Comment by ddude** [comment]
If it helps, I'm directly compiling against the master branch on all three of linux, osx and windows and it works great!

**Comment by aldacron** [comment]
Took me a few days longer to decompress than I had expected, but I finally got around to this. The 3.1 branch has the native stuff in it now and a 1.1.1 release has been tagged. The DUP repo should pick it up shortly. Thanks!

**Comment by ddude** [comment]
Awesome, thanks!
