### ISSUE TITLE
Most of the vulkan support functions are not exposed

### ISSUE THREAD

**Issue by ParticlePeter** [DerelictOrg/DerelictGLFW3#8]
Exposed:
`glfwVulkanSupported`

Not exposed:
`glfwGetRequiredInstanceExtensions`
`glfwGetInstanceProcAddress`
`glfwGetPhysicalDevicePresentationSupport`
`glfwCreateWindowSurface`

Missing Enums:
`GLFW_NO_API`
`GLFW_TRUE`
`GLFW_FALSE`

Required additions:

```
enum GLFW_NO_API = 0;
enum GLFW_TRUE = 1;
enum GLFW_FALSE = 0;

extern(C) @nogc nothrow {

    alias GLFWvkproc = void function();

    alias da_glfwGetRequiredInstanceExtensions = const(char*)* function(uint*);
    alias da_glfwGetPhysicalDevicePresentationSupport = int function(VkInstance, VkPhysicalDevice, uint);
    alias da_glfwGetInstanceProcAddress = GLFWvkproc function(VkInstance, const(char)*);
    alias da_glfwCreateWindowSurface = VkResult function(VkInstance, GLFWwindow*, const(VkAllocationCallbacks)*, VkSurfaceKHR*);
}

__gshared {
    da_glfwGetRequiredInstanceExtensions glfwGetRequiredInstanceExtensions;
    da_glfwGetPhysicalDevicePresentationSupport glfwGetPhysicalDevicePresentationSupport;
    da_glfwGetInstanceProcAddress glfwGetInstanceProcAddress;
    da_glfwCreateWindowSurface glfwCreateWindowSurface;
}

class DerelictGLFW3Loader : SharedLibLoader {
    public this() {
        super(libNames);
    }

    protected override void loadSymbols() {
        super.loadSymbols();

        bindFunc(cast(void**)&glfwGetRequiredInstanceExtensions,"glfwGetRequiredInstanceExtensions");
        bindFunc(cast(void**)&glfwGetPhysicalDevicePresentationSupport,"glfwGetPhysicalDevicePresentationSupport");
        bindFunc(cast(void**)&glfwGetInstanceProcAddress,"glfwGetInstanceProcAddress");
        bindFunc(cast(void**)&glfwCreateWindowSurface,"glfwCreateWindowSurface");
    }
}
```

Sidenote:
I read your comment in module `derelict.glfw3.statfun`
The above code is working in practice. Firstly its explained [here](https://github.com/ColonelThirtyTwo/dvulkan/wiki/Using-d-vulkan-with-Derelict-GLFW), secondly a working example can be found [here](https://github.com/ParticlePeter/ErupteD-GLFW). In the second case derelictGLFW3 v2.0.0 dynamic binding is used, the additional features are added to a class which derives from DerelictGLFW3Loader and glfw3 was build from source-head at that time.
As soon as you add those additions I will update the example to DerelictGLFW3 v3.0.0.

**Comment by mdparker** [comment]
Please read [my blog post](http://dblog.aldacron.net/) where I talk about this issue. I don't like the idea of creating an entirely new loader just for a handful of functions, especially since it doesn't solve the problem with the types of the return values and function parameters.

**Comment by mdparker** [comment]
Actually, I worded that wrong. I do want to create a new loader for the vulkan stuff, but I was thinking of just implementing a function as part of the mixin solution. A subclass of DerelictGLFW3 would do the job do, but it would need to be part of the mixin.

**Comment by mdparker** [comment]
> Exposed:
> glfwVulkanSupported

This is part of the core GLFW API.

> Not exposed:
> glfwGetRequiredInstanceExtensions
> glfwGetInstanceProcAddress
> glfwGetPhysicalDevicePresentationSupport
> glfwCreateWindowSurface

These are conditionally compiled only when Vulkan is available.

> GLFW_NO_API
> GLFW_TRUE
> GLFW_FALSE

I must have overlooked these.

**Comment by ParticlePeter** [comment]
I read the blog, and that made me think.
I do not see a problem in specifying a configuration where the vulkan support functions would be loaded, but I see an issue with the types as you explained. As a matter of fact in the working example which I mentioned I use types from erupted vulkan binding when I subclass from `DerelictGLFW3Loader`.

Here is a suggestion, but supervising work from your side would be required.
You need a reliable DerelictVulkan binding which could be imported via a dub configuration when vulkan is supposed to be used with glfw3. The types would be taken from that official DerelictVulkan binding.

Currently three vulkan bindings exist, one of them has taken the name DerelictVulkan. Unfortunately it seems to work only on windows and is still WIP (last commit two month ago).
The other two bindings D-Vulkan and ErupteD (mine) are both auto-generated. In fact ErupteD were lot of ignored pull requests for D-Vulkan. After a while the owner replied but was not convinced of the suggestions.

I can offer you ErupteD as DerelictVulkan, but which of the bindings you want is for you to decide and get in touch with the other two owners.

**Comment by mdparker** [comment]
OK, I've implemented it using template mixins. I did the same for all of the conditionally compiled native functions, too. You can see it at the bottom of dynload.d in the master branch. The Windows native loader was the only thing I was able to test at the moment. I will get around to testing the Mac, X11 and possible the EGL stuff later. I can't test Vulkan, Wayland, or Mir (AFAIK).

Here's an example of how to implement the Vulkan loader:

```D
import derelict.glfw3;
import erupted; // Or any Vulkan binding

mixin DerelictGLFW3_VulkanBind;

void loadGLFW() {
    DerelictGLFW3.load();
    DerelictGLFW3_loadVulkan();  // Note the underscore -- not a member function
}
```

The native stuff is similar. For example:

```D
version(Windows) import core.sys.windows.windows : HWND, HGLRC;

mixin DerelictGLFW3_NativeBind;  // alias for DerelictGLFW3_Windows/Mac/X11Bind

void loadNative() {
    DerelictGLFW3_loadNative();  // alias for DerelictGLFW3_loadWindows/Mac/X11
}
```

Please let me know how the Vulkan loader works for you. If all is well with that, Mac, and X11, then I will tag a new 3.1 release, since I removed some Mac & Window functions out of the main API and put them in the mixins.

**Comment by mdparker** [comment]
I didn't see your last comments until after I posted my new one.

> You need a reliable DerelictVulkan binding which could be imported via a dub configuration when vulkan is supposed to be used with glfw3. The types would be taken from that official DerelictVulkan binding.

The problem with that approach is that it would couple the DerelictGLFW3 binding with DerelictVulkan and preclude using it with other bindings. It's the same problem I would have declaring the types in DerelcitGLFW3 itself.

Actually, this problem extends to the system-specific stuff in DerelictGL3 and DerelictSDL2. It's just that those aren't generally used with external system bindings in a way that causes the conflict. I do intend to change DerelictGL3 to use the template mixins, though. It will let me trim things down a tiny bit.

**Comment by ParticlePeter** [comment]
> The problem with that approach is that it would couple the DerelictGLFW3 binding with DerelictVulkan

That's a point but I thought that you would intend a smooth cooperation between Derelict bindings in general. Using other bindings would still be possible, all it needs is a configuration without the vulkan related functions. In that case a workflow similar to the erupted-glfw example would still work with any binding.
However, if you are satisfied with your solution its fine for me, I will test it now and report.

**Comment by ParticlePeter** [comment]
Typo, must be VkInstance:

    alias da_glfwGetInstanceProcAddress = GLFWvkproc function(Vkinstance,const(char)*);

Parameter const(VkAllocationCallbacks)* must be a pointer:

    alias da_glfwCreateWindowSurface = VkResult function(VkInstance,GLFWwindow*,const(VkAllocationCallbacks),VkSurfaceKHR*);

Then the test case works.
I will add that to the erupted-glfw example.

**Comment by mdparker** [comment]
OK, thanks. I'll get the static binding updated tomorrow and push a new release.

**Comment by mdparker** [comment]
I guess this is all working now and I just forgot to close it?

**Comment by ParticlePeter** [comment]
Yes, sorry :-)
