### ISSUE TITLE
Failed to load symbol "glfwSetWindowIcon"

### ISSUE THREAD

**Issue by jython234** [DerelictOrg/DerelictGLFW3#9]
I'm using Fedora 24 (kernel 4.7.5, 64bit)
I have the latest GLFW version installed, which is 3.1 (from DNF)

Traceback:
```
derelict.util.exception.SymbolLoadException@../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/exception.d(35): Failed to load symbol glfwSetWindowIcon from shared library libglfw.so.3
----------------
../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/sharedlib.d:177 void* derelict.util.sharedlib.SharedLib.loadSymbol(immutable(char)[], bool) [0x4a00f9]
../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/loader.d:323 void* derelict.util.loader.SharedLibLoader.loadSymbol(immutable(char)[], bool) [0x49e5ac]
../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/loader.d:346 void derelict.util.loader.SharedLibLoader.bindFunc(void**, immutable(char)[], bool) [0x49e682]
../../.dub/packages/derelict-glfw3-3.1.0/derelict-glfw3/source/derelict/glfw3/dynload.d:283 void derelict.glfw3.dynload.DerelictGLFW3Loader.loadSymbols() [0x49d43d]
../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/loader.d:198 void derelict.util.loader.SharedLibLoader.load(immutable(char)[][]) [0x49e214]
../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/loader.d:143 void derelict.util.loader.SharedLibLoader.load(immutable(char)[]) [0x49e107]
../../.dub/packages/derelict-util-2.0.6/derelict-util/source/derelict/util/loader.d:82 void derelict.util.loader.SharedLibLoader.load() [0x49df61]
../git/mango-engine/source/mango_engine/graphics/opengl/gl_backend.d:122 shared(void function()) mango_engine.graphics.opengl.gl_backend.GLBackend.loadGLFW [0x47e0ab]
../git/mango-engine/source/mango_engine/graphics/opengl/gl_backend.d:70 shared(void function(const(immutable(char)[][immutable(char)[]]))) mango_engine.graphics.opengl.gl_backend.GLBackend.loadLibraries [0x47deee]
../git/mango-engine/source/mango_engine/mango.d:89 void mango_engine.mango.mango_init(mango_engine.mango.GraphicsBackendType) [0x47dd0d]
source/app.d:6 _Dmain [0x47cec6]
??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x4a42ee]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4a4238]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).runAll() [0x4a42aa]
??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x4a4238]
??:? _d_run_main [0x4a41a9]
??:? main [0x47d49f]
??:? __libc_start_main [0x1bd10730]
```

I thought at first this was a version mismatch, but GLFW and the library both are 3.1, so I'm not sure what the problem is.

**Comment by mdparker** [comment]
From the DerelictGLFW3 master branch README:
> A dynamic and static binding to version 3.2 of the GLFW 3 library for the D Programming Language.

And from the [DerelictGLFW3 documentation](https://derelictorg.github.io/packages/glfw3.html), which is linked from the README:

>DerelictGLFW3 1.0.x is a dynamic binding to the 3.0 series of GLFW and DerelictGLFW3 1.1.x is a dynamic binding to the 3.1 series. DerelictGLFW3 2.0.x provides both static and dynamic bindings to GLFW3 3.1. DerelictGLFW3 3.0.x and 3.1.x provide the same for GLFW 3.2. 3.1.x includes support for all of the optional GLFW 3.2 functions that are conditionally compiled.

So with that, you see that for GLFW 3.1, you should be using DerelictGLFW3 1.1.x. The last release in that series was 1.1.1. The Derelict package versions do not correspond to the version of the libraries to which they bind. That's just not practical, given that each package has its own bug fix releases and new feature releases independent of the C libraries. 

Currently, only a couple of packages are documented, but all of the info you need is available in the repositories of each package, in the README files and the tags lists. The README in the master branch for each package will show you which version of the C library the latest release supports. If you need an older version of a C library, look at the README's of other branches in the Derelict package to find it, then find the tag that corresponds to the most recent commit in that branch. Where practical, some Derelict packages, like DerelictSDL2, support loading specific versions of a library with SharedLibVersion (though DerelictGLFW3 does not and will not).

**Comment by jython234** [comment]
@mdparker Thank You! I understand now, the difference in versions threw me off.
